### PR TITLE
8 dof URDFs

### PR DESCRIPTION
**Pull request by ipa-nhg**

### CODE REVIEW

**Comment by ipa-nhg** [comment]
Merge togetehr with https://github.com/squirrel-project/squirrel_common/pull/142

**Comment by ipa-nhg** [comment]
@edith-langer did you test this version? @bajo could it be merged? laso https://github.com/squirrel-project/squirrel_common/pull/142

**Comment by bajo** [comment]
@ipa-nhg I did not test it, so I would not merge it. @edith-langer is on sick-leave today. I hope she can tell us if she tested it and if it worked in a few days.

**Comment by edith-langer** [comment]
I tested it with the current navigation package and tuw-robotino in simulation. It is not working for me with the tuw-robotino2 though.

**Comment by ipa-nhg** [comment]
Real robot or simulation?

**Comment by edith-langer** [comment]
In simulation.
Have not tried anything on the real robot after the integration meeting.

**Comment by ipa-nhg** [comment]
could please be tested on the robot? the tuw-robotino2 and uibk-robotino2 urdf/description are from Simon. I can use my urdf for all the robots (like uibk-robotino), but then you will not able to plan with 8dof... @mzillich what should we do?

**Comment by mzillich** [comment]
We will test on our real robot next. Let's see if that helps figuring out the problem.

**Pull request merged**
