### PR TITLE
new pan_tilt mesh model

### PR DESCRIPTION
**Pull request by ipa-nhg**

### CODE REVIEW

**Comment by ipa-nhg** [comment]
Fixed the pan-tilt profile to the base. For example for uibk-robotino2 looks:

screenshot from 2016-03-15 16 31 52

@lokalmatador can you please check (visual) if it is right, I haven't got the hardware, I used a photo as reference.... Looks like your hardware?

**Comment by ipa-nhg** [comment]
@lokalmatador can be merged?

**Comment by ghost** [comment]
I'm sick at home, but it looks good. Definitely better than the old one. I can check it tomorrow though.

**Comment by ghost** [comment]
Just checked it visually, looks fine!

**Pull request merged**
