### PR TITLE
Arm review

### PR DESCRIPTION
**Pull request by ipa-nhg**

### CODE REVIEW

**Comment by ipa-nhg** [comment]
Thanks @philkark
@philkark @lokalmatador @mzillich please review

**Comment by ghost** [comment]
LGTM though cannot test. But I guess it's fine.

**Comment by tpatten** [comment]
See comments in https://github.com/squirrel-project/squirrel_common/pull/235

**Comment by ipa-nhg** [comment]
This PR should be ok, it is updating the mount position of the arms and move the arm by default to the folded position on simulation, after the merge of https://github.com/squirrel-project/squirrel_common/commit/9658e6e75fa022cb248a7cb5af81ff9574efd4d0 should work.

**Pull request merged**
