### PR TITLE
added arm to alufr-robotino

### PR DESCRIPTION
**Pull request by ipa-nhg**

### CODE REVIEW

**Comment by ipa-nhg** [comment]
@federico-b  please review

**Comment by ghost** [comment]
You reverted the odometry to the initial version? That's fine if we don't have those problems with
delay in the odometry. Let's check if the robotino doesn't have that problem any longer (it has not been
shipped yet), otherwise we keep the new ones.

**Comment by ipa-nhg** [comment]
Yes, I had a broken tf tree with our version. Also Festo updated all the drivers of the robot, I will use my platform to test and update the robotino_driver package, maybe it also helps.

**Comment by ipa-nhg** [comment]
it has to be updated to use the new structure , this PR can be closed

**Pull request closed without merging**
