### PR TITLE
create a config folder per robot

### PR DESCRIPTION
**Pull request by ipa-nhg**

### CODE REVIEW

**Comment by ipa-nhg** [comment]
@edith-langer can you please test this version on your robotino?

**Comment by edith-langer** [comment]
error loading <rosparam> tag: 
        file does not exist [/home/squirrel/catkin_ws/src/squirrel_robotino/robotino_bringup/tuw-robotino/config/pan_tilt.yaml]

you are missing the robots-folder

**Comment by ipa-nhg** [comment]
@edith-langer done!

**Comment by edith-langer** [comment]
@ipa-nhg looks good on our robot now!

**Comment by ipa-nhg** [comment]
Thanks @edith-langer

**Pull request merged**
