### PR TITLE
udpated configuration

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ipa-nhg** [comment]
after the calibration process?  the position of the pan-tilt profile (and the camera) looks estrange

screenshot from 2016-03-15 15 09 50

I will change the model and give to the profile a fix position

**Comment by ghost** [comment]
Hm, it really looks interesting. But we checked it with Rviz, i.e., displaying a point cloud and the image from the kinect and they both looked fine: the wall was perpendicular to the floor and the floor was parallel to the grid; and yes, we got that values from Richard's calibration routine after calibrating the laser with Federico's routine.

**Comment by ipa-nhg** [comment]
OK! Merged

**Comment by ipa-nhg** [comment]
https://github.com/squirrel-project/squirrel_robotino/pull/100

**Pull request merged**
