### PR TITLE
added a virtual odomp frame

### PR DESCRIPTION
**Pull request by ipa-nhg**

### CODE REVIEW

**Comment by ipa-rmb** [comment]
Visual review ok

**Comment by Senka2112** [comment]
Hi Nadia,

there is no error now but localization is still not working. When I run navigation package with this version (robotino with arm) robot is kind of jumping on the map and pose is not updated correctly. It seems like two different nodes are publishing the same frame.

Also is there removed package 'package://robotino_description/meshes/RobotinoBody.stl' which is needed for navigation visualisation (not causing any issues for just error is reported and there is no tf for the wheels in rviz)

Also by launching the simulation this warning occurs:
 [WARN] [WallTime: 1447779450.701294] [45.925000] Controller Spawner couldn't find the expected controller_manager ROS interface.

Senka

**Comment by ipa-nhg** [comment]
Hi Senka,

There are 3 different topics:
- I think that the actual arm description is not compatible with the squirrel navigation package. Did you try the navigation on the real robot? with the arm?  I  dont know why the arm manipulation needs an extra odometry frame, I just did the same changes that the arm developers required. Are you using the /odomp frame? is it necessary? 
- The mesh file warning is not because of the navigation, you should get also this error is you just try to spawn the RobotModel with rviz (rosrun rviz rviz), the file is there I didn't remove it https://github.com/squirrel-project/squirrel_robotino/blob/indigo_dev/robotino_description/meshes/RobotinoBody.stl , I just updated the model because our model was wrong (too small). It can be that you get this error because of your graphic card , I can try to simplify the model. But do you see the body of the robotino? or is it missed?
- the controller_manager is a ROS package, I am not the maintainer, I imagine that the node has a timeout and if don’t get a message during some time you get this WARNING , but are you able to move the arm? and the robot? Is it also possible that you have this error because, at the moment, we spawn all the controllers together , that means also the tilt_controller and you doesn't have this component on your description. I will divide the controllers as soon as I have time. But if you can move your arm, just ignore the warning.

Please let me know if you need the odomp frame, if yes, we have to talk with the arm and the navigation developers and find a solution together.

**Comment by Senka2112** [comment]
Hi Nadia,

first topic:
 we didn't test it at robotino on the real robot beacuse we cannot even clone the squirrel_robotino since it is coliding with the configurations and robotino directory which festo put on it. (as well the squirrel_arm). Also tree is not connected properly. At the integreation meeting there will be also festo representative who worked on this so we can all take a look together how to integrate it properly.  Maybe they should make changes for the arm control

second: I see the body of robotino and everything is there (navigation and localizsation is working for the case without arm). Just there is that error there is no transformation for wheels. Any case it seems  that is  not affecting any package at the moment so we can ignore it for the moment

third: yes it is possible to move the arm. I just put it there since that is also irregularity and migth be connected with this first topic (but probably it is not)

At the moment I am working with the robotino without arm in simulation so for me is ok, but phillip and simon might need it

Thanks
Senka

**Comment by Senka2112** [comment]
PS we are not using /odomap. I don't know why it is there

**Pull request merged**
