### PR TITLE
Add shell front collision to the real robot robot_description

### PR DESCRIPTION
**Pull request by ipa-nhg**

### CODE REVIEW

**Comment by ipa-nhg** [comment]
Please test and merge together with https://github.com/squirrel-project/squirrel_common/pull/243

@mzillich @lokalmatador @philkark @smhaller 
This should solve the problem, I added a xacro argument:
-  if the argument (for the real robot) is true the robot collision looks:
image
- if the argument (for the simulation) is false: 
image

**Comment by mzillich** [comment]
hm, but we still need the robotino base collision checks also for the real robot. so that should not be removed.

**Comment by ipa-nhg** [comment]
the base collision model was not removed, sorry I didn't display it on the first screenshot but it is still there

**Comment by ipa-nhg** [comment]
@mzillich, already tested?

**Comment by mzillich** [comment]
@tpatten is no it

**Comment by tpatten** [comment]
I will test this tomorrow. Is there anything in particular that I should do, like try to move the arm really close to the shell?

**Comment by mzillich** [comment]
@tpatten yes, would be good. like UIBK did, i.e. trying to grasp with the hand "pointing forward"

**Comment by tpatten** [comment]
I can't get the launch to run. There is an error due to the introduction of the "real" argument in robotino.urdf.xacro



Traceback (most recent call last):
  File "/opt/ros/indigo/share/xacro/xacro.py", line 62, in <module>
    xacro.main()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/xacro/__init__.py", line 696, in main
    eval_self_contained(doc)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/xacro/__init__.py", line 626, in eval_self_contained
    eval_all(doc.documentElement, macros, symbols)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/xacro/__init__.py", line 526, in eval_all
    (str(name), str(node.tagName)))
xacro.XacroException: Invalid parameter "real" while expanding macro "xacro:shell"
Invalid <param> tag: Cannot load command parameter [robot_description]: command [/opt/ros/indigo/share/xacro/xacro.py '/u/vienna/catkin_ws/src/squirrel_robotino/robotino_bringup/robots/tuw-robotino2/urdf/robotino.urdf.xacro'] returned with code [1]. 

Param xml is <param command="$(find xacro)/xacro.py '$(find robotino_bringup)/robots/$(arg robot)/urdf/robotino.urdf.xacro'" name="robot_description"/>
The traceback for the exception was written to the log file

**Comment by ipa-nhg** [comment]
did you also merge squirrel_common?? squirrel-project/squirrel_common#243 (https://github.com/squirrel-project/squirrel_robotino/pull/219#issuecomment-361168155)

**Comment by tpatten** [comment]
Sorry. I didn't read the comment. The launch file works now.

**Comment by tpatten** [comment]
I've tested at least 20 different end effector poses (including hand pointing forwards) and no plans generate a collision. But then again, I never saw this before with our robot so I can't verify, only test. At least nothing goes wrong so on my side it looks good :) UIBK definitely allowed the base to move right?

**Comment by ipa-nhg** [comment]
Thanks for testing! :)

**Pull request merged**
