### PR TITLE
added the shell model and controllers to UIBK robotino

### PR DESCRIPTION
**Pull request by ipa-nhg**

### CODE REVIEW

**Comment by ipa-nhg** [comment]
@lokalmatador this version will be needed as soon as your robot is back

**Comment by ghost** [comment]
OK!

**Comment by ipa-nhg** [comment]
@bajo @Senka2112 this should be the new configuration for uibk-robotino2

**Comment by mzillich** [comment]
So should this be merged then?

**Comment by ipa-nhg** [comment]
yes, but once uibk-robotino2 has a scrat pc and the NFS system is configured

**Comment by ipa-nhg** [comment]
@lokalmatador the shell is also included, in case you can't see it with RVIZ check your sourced workspace

**Comment by ipa-nhg** [comment]
Can this me merged? @lokalmatador

**Comment by ghost** [comment]
I guess yes.

**Pull request merged**
