### PR TITLE
review base simulation

### PR DESCRIPTION
**Pull request by ipa-nhg**

### CODE REVIEW

**Comment by ipa-nhg** [comment]
@qusaisuwan @shangl I created a second URDF description robotino_base_plan.urdf.xacro , you can use this model to create the urdf required by Moveit! to plan trajectories and not modify the urdf (robotino.urdf.xacro) that is needed by the other component drivers and the simulation.

This PR is needed https://github.com/squirrel-project/squirrel_common/pull/130/  and this commit https://github.com/squirrel-project/squirrel_common/pull/130/commits/8bc91df529f8a74372d0ede08dfd70da90d94cf0 should decrease the time needed to find a trajectory with Moveit!

**Comment by shangl** [comment]
@ipa-nhg : i really would like to stress that the hand was removed because it was originally added without any testing and the flaws were just to big for us to repair it (we tried it initially to solve it temporarily and it cause one problem after another) - so it should not be in the productive indigo_dev branch until this issue is resolved. i further have to emphasize that there is no safe planning until then (either the hand is not included in the collision checking (in case the model stays removed) or it is not working at all due to continuous collisions (in case the model is added again)). ( @qusaisuwan , @Senka2112 , @lokalmatador , @mzillich , @bajo )

**Comment by ipa-nhg** [comment]
@edith-langer @bajo please review this version of the simulation

@qusaisuwan the base can not be moved with the 8dof topic on simulation, could you please take a look on https://github.com/squirrel-project/squirrel_driver/blob/new_structure/uibk_robot_driver/src/ArmControllerSim.cpp#L82 ?

**Comment by qusaisuwan** [comment]
@ipa-nhg I have never seen this file before (ArmControllerSim.cpp). Did you add it? I think the code inside it follows the old architecture which I completely changed.

**Comment by ipa-nhg** [comment]
@qusaisuwan yes, I added it to use the same move base code that use the real node for the simulation, how should it looks now?  what did you change? Thanks!

**Comment by qusaisuwan** [comment]
@ipa-nhg I am not sure I get how the functionality of the code in the ArmControllerSim.cpp should work. But in general, using the new architecture, you should create a RobotController object, instantiate it, then enable the base and the arm and add their parameters. and then use the function moveAll passing 8 values to it representing the target joint state.
Something like this:
shared_ptr<RobotController> robotinoController= shared_ptr<RobotController>(new RobotController(node,freq));
    robotinoController->initBase();
    robotinoController->initArm({1, 2, 3, 4, 5},
    {DYNAMIXEL_BIG_MOTOR, DYNAMIXEL_BIG_MOTOR, DYNAMIXEL_BIG_MOTOR, DYNAMIXEL_SMALL_MOTOR, DYNAMIXEL_SMALL_MOTOR},
                                                {std::make_pair<double, double>(-125000.0 / Motor::TICKS_FOR_180_DEG_BIG \* M_PI, 130000 / Motor::TICKS_FOR_180_DEG_BIG \* M_PI),
                                                 std::make_pair<double, double>(-140000 / Motor::TICKS_FOR_180_DEG_BIG \* M_PI, 185000 / Motor::TICKS_FOR_180_DEG_BIG \* M_PI),
                                                 std::make_pair<double, double>(-150000 / Motor::TICKS_FOR_180_DEG_BIG \* M_PI, 150000 / Motor::TICKS_FOR_180_DEG_BIG \* M_PI),
                                                 std::make_pair<double, double>(-100000 / Motor::TICKS_FOR_180_DEG_SMALL \* M_PI, 100000 / Motor::TICKS_FOR_180_DEG_SMALL \* M_PI),
                                                 std::make_pair<double, double>(-140000 / Motor::TICKS_FOR_180_DEG_SMALL \* M_PI, 140000 / Motor::TICKS_FOR_180_DEG_SMALL \* M_PI)});

 robotinoController->moveAll(moveCommandState);

Also, you can look at robot_controller_node.cpp as an example.
I hope this helps!

**Comment by ipa-nhg** [comment]
@qusaisuwan  I will try your suggestion

**Comment by shangl** [comment]
@qusaisuwan : are you aware that this is about simulation? the initArm command will try to establish a connection to the real arm

**Comment by ipa-nhg** [comment]
@shangl @qusaisuwan actually I only want to move the base, the arm movements are already implement on the simulation. 

I just want to take the commanded position goal for the base ( the first 3 values of the robotino_arm/joint_control/move topic) and send a cmd_rotatory to the base (geometry_msgs/Twist)

**Comment by shangl** [comment]
i dont know how much qusai changed but in general the base controller should already do exactly that. you can just use it without copying the code (is that still correct qusai?)

**Comment by qusaisuwan** [comment]
@ipa-nhg @shangl I see. What @shangl said is correct. It should work pretty fine with this implementation. I cannot see what's the problem if this is not working.

**Comment by ipa-nhg** [comment]
@ipa-rmb @edith-langer @mzillich could you please review this PR?

**Comment by ipa-rmb** [comment]
looks good

**Pull request merged**
