### PR TITLE
created a calibration metapackage

### PR DESCRIPTION
**Pull request by ipa-nhg**

### CODE REVIEW

**Comment by ipa-nhg** [comment]
This pull request has to be merged together with https://github.com/squirrel-project/squirrel_calibration/pull/1

**Comment by ipa-nhg** [comment]
@ipa-rmb please review

**Comment by ipa-rmb** [comment]
looks good

**Comment by ipa-rmb** [comment]
i cannot merge squirrel-project/squirrel_calibration#1 (permissions), hence I will not do this merge now.

**Pull request merged**
