### PR TITLE
New structure merge 

### PR DESCRIPTION
**Pull request by ipa-nhg**

### CODE REVIEW

**Comment by ipa-nhg** [comment]
@shangl on this PR are all the urdf models(all the robots) reviewed and tested. I created a special urdf file for planning ( input for MoveIt!) , https://github.com/squirrel-project/squirrel_robotino/blob/new_structure/robotino_bringup/robots/uibk-robotino2/urdf/robotino_base_plan.urdf.xacro where the collision of the base is a primitive shape (a cylinder) , please modify this urdf to be able to plan trajectories (e.g. substitute  the model of the hand with a sphere), the modifications of this file will not affect to the sim model, robot state publisher or other drivers. The makefile will take this robotino_base_plan.urdf.xacro to generate the robotino.urdf used by MoveIt! https://github.com/squirrel-project/squirrel_robotino/blob/new_structure/robotino_bringup/robots/uibk-robotino2/urdf/makefile 

(you need also this PR https://github.com/squirrel-project/squirrel_common/pull/132)
@mzillich FYI

**Comment by shangl** [comment]
@ipa-nhg : as stated in emails 2 weeks ago the problem is not the complex shapes, but the faulty model. the hand collides with the arm in its standard configuration. there is no need for a separate and duplicate (and especially potentially out-of-sync) model. planning works as soon as this collision is gone.

further there are several problems with using a sphere for the hand. one example: the sphere (or cylinder, ...) will have to be as large as the maximum stretch of the hand in order to make it safe. in that case the kinesthetic teaching @qusaisuwan implemented wont be able to move down to the ground because it checks collisions all the time. there is no way around fixing the problem of the colliding hand

@mzillich @piater @Senka2112 @lokalmatador @qusaisuwan

**Comment by ipa-nhg** [comment]
@shangl what about configure Moveit to ignore the collision between hand and arm_4_link/arm_5_link?? Without a hand on the robot_description we will not be able to launch the hand driver, neither move the hand, than include the hand on the  robotino.urdf.xacro is a mandatory. If you want a hand model without collision you have to discuss it  with @sunjiekcl , the maintainer of the `kclhand_description` package.

If it is required for the manipulation you can also remove the hand on https://github.com/squirrel-project/squirrel_robotino/blob/new_structure/robotino_bringup/robots/uibk-robotino2/urdf/robotino_base_plan.urdf.xacro#L38 , but I think that you should consider that you have a hand attached to plan trajectories.

**Comment by shangl** [comment]
@ipa-nhg thats what i did initially but then more and more links of the hand started colliding with the arm (i disabled 2 collisions before i kicked out the hand of the model - maybe you remember: you saw it in my commit and said i should not disable these collisions).

yes, i perfectly understand that it has to be in the model - i only removed it temporarily because it affects other components and is rather easy to resolve. i already reported the problem to @mzillich , kcl ( @sunjiekcl ) and ipa ( @ipa-nhg ).

yes, i agree thats why i say planning without a working hand model in the robot model is not an option (unsafe).

in general: its fine for me to put it the hand model back to the overall robot model. it should just be clear that planning and kinesthetic teaching wont work in that case until this issue is fixed ( @mzillich @piater @Senka2112 @lokalmatador ). this also was communicated like this in emails. further, i think this issue also was showing in our case because the hand was in the model even though the hand was not mounted - this wont be the general case. the hand will be mounted at some point and will have updated joint values (hopefully without collisions) - so the problem will probably disappear anyways. still, i think, the problem should nevertheless be resolved in order to make the complete system more stable.

**Comment by ipa-nhg** [comment]
I think that you will have to define the ignored collisions because of the kinematic of the hand. Moveit! is able to detect the collision between parents and children , but on the case of this hand the end of the chain is conected (phisically) to the first link , and it is not defined on the URDF ( @sunjiekcl correct me if I am wring)  , I think that at least this collision should be considered.

@shangl  You can debug the errors using Moveit! , after load the model the RVIZ interface of Moveit (`Motion Planning`) under the `Status` tab will show you all the problems that has currently Moveit! to plan a trajectory. You can add all the collisions between hand link and other hand link  to https://github.com/squirrel-project/squirrel_manipulation/blob/indigo_dev/uibk_moveit_config/config/robot.srdf#L27

For you is important to check the collisions between the hand and the floor, hand and shell or hand and robotino body, the collision between the fingers should not be relevant to plan a trajectory with the arm, what do you think @lokalmatador ?

**Comment by ghost** [comment]
Yes, @ipa-nhg is right: as long as we can assure that the hand does not crash into anything we're good. Collision among the fingers of the hand can be safely ignored, as they - in real - never really happen. Virtually they were just there because of the (sometimes) wrong values published by the finger's joint state publisher.

**Comment by shangl** [comment]
i am not sure if i completely understand the first paragraph. the moveit sampler detects automatically collisions that may occur and disables them. i think we should discuss at the integration meeting what exactly is the best way to go forward in that case. to me it sounds hard to believe that it is not possible to define the standard configuration such that the fingers are not colliding with the arm

the disadvantage in disabling these collisions is that it will be possible then to plan trajectories that might rip off fingers by making them collide with the arm. if there is really no other solution, i guess, we will still have to disable the collisions

@lokalmatador @ipa-nhg : it is not a collision between fingers. it is a collision between the fingers and arm links in the default configuration.

**Comment by shangl** [comment]
checked it again. one collision i wrote down was between hand_base_link and hand_right coupler . this specific one is just within the hand model (and probably can be disabled safely?). i will also check all the other collisions at the integration meeting and disable them as a quick-and-dirty solution.

**Comment by ghost** [comment]
Yes, if it is collisions between fingers, I'd just disable them.

**Comment by shangl** [comment]
@lokalmatador : i cannot say yet whether its only collisions between hand links. when we tried it, as soon as we disabled a collision, another one popped up (that was the reason why we kicked out the hand model). at the integration meeting i will try to disable all pairwise hand link combinations and check if it is working then

**Comment by ghost** [comment]
@shangl : ok great.

**Comment by ipa-rmb** [comment]
Hi folks, would it be possible that @lokalmatador verifies which collisions occur within the hand and disable those for @shangl so that Simon can focus on testing planing with a (hopefully then) working MoveIt model before the integration meeting? I have seen this job done by colleagues some time ago and it took them 10 minutes, so it might be worth trying.

**Comment by ghost** [comment]
Well, I can have a look at it on Thursday as I have a skype call with @sunjiekcl . Otherwise we may have to postpone it to the integration meeting. which branch would I need, which models do I have to load and where shall I look for those collisions?

**Comment by ipa-nhg** [comment]
`git@github.com:squirrel-project/squirrel_robotino -b new_structure`
`git@github.com:squirrel-project/squirrel_common -b new_structure`
`git@github.com:squirrel-project/squirrel-driver -b new_structure` ( @shangl  also https://github.com/squirrel-project/squirrel_driver/pull/43 ? )

@shangl and for `squirrel_manipulation`  ?

**Comment by ipa-rmb** [comment]
Looks good

**Pull request merged**
