### PR TITLE
Twist mux

### PR DESCRIPTION
**Pull request by ipa-nhg**

### CODE REVIEW

**Comment by ipa-nhg** [comment]
the twist mux is used to define the priority of the velocity  commands : http://wiki.ros.org/twist_mux

please @federico-b update your navigation to command /navigation_cmd instead of /cmd_vel, you can just remap the topic like the following example https://github.com/ipa-nhg/squirrel_robotino/blob/twist_mux/robotino_bringup/robots/uibk-robotino2/launch/uibk-robotino2.launch#L47

@Senka2112 pushing should command /pushing_cmd

**Comment by ghost** [comment]
Hi Nadia, 

ok, but careful because the actual command topic is robotino_cmd_vel (we defined that in the robotino_safety_node).

**Comment by ipa-nhg** [comment]
@federico-b are robotino_safety_node changes alrready  commited and merged?

**Comment by ghost** [comment]
So as it is now, the drivers subscribe to `/robotino_cmd_vel`, the navigation publish `/cmd_vel`, and 
robotino_safety_node subscribe to `/cmd_vel` and publishes `/robotino_cmd_vel~. How to you want exactly the things to work?

navigation publishes `/navigation_cmd_vel`
drivers subscribes to ?
robotino_safety_node ?

My guess is navigation publishes `/navigation_cmd_vel_raw` (not be feed into the mux stuff),
robotino_safety takes `/navigation_cmd_vel_raw` and publishes `/navigation_cmd_vel` and the drivers subscribe to `/cmd_vel`. Do you agree?

**Comment by ipa-nhg** [comment]
I think that the architecture should looks:

unbenannt

twist mux is just used to decide which component has priority, our problem was that if we started the manipulation, the rotatory controller of the base (6 DOF modus) is constantly publishing a velocity to the base (angular.z) , and we were not ablo to command to the same topic /cmd_vel with the navigation or pushing because the /cmd_vel topic was blocked. With the twist_mux we subcribes to /cmd_navigation. /cmd_rotatory and /cmd_pushing and decide which one should be active. The order that I set is first navigation, second pushing and rotatory the last one.

**Comment by ghost** [comment]
It's clear now,  I'll do it.

**Pull request merged**
