### PR TITLE
package restructuration and clean up

### PR DESCRIPTION
**Pull request by ipa-nhg**

### CODE REVIEW

**Comment by ipa-nhg** [comment]
Merge together with https://github.com/squirrel-project/squirrel_common/pull/122 and https://github.com/squirrel-project/squirrel_driver/pull/24

**Comment by bajo** [comment]
@ipa-nhg not sure if this can compile with the new structure. 
`robotino_bringup: Cannot locate rosdep definition for [robotino_safety]` 
Looks like robotino_bringup has a dependency which is no longer reachable as robotino_safety is in the private squirrel_driver repository

**Comment by ipa-nhg** [comment]
Yeap, I can create  dummy nodes for robotino_safety and robotino_driver on squirrel_substitute, it should be enough to compile the repository with travis.

My plan is update and make public `squirrel_driver` , and release it together with  `squirrel_common` and `squirrel_robotino` after the review meeting, theoretically `squirrel_substitute` will not be needed anymore!

**Comment by bajo** [comment]
That sounds like a good plan. Thanks.

**Comment by ipa-nhg** [comment]
After https://github.com/squirrel-project/squirrel_substitute/pull/4 Travis is happy!

**Comment by bajo** [comment]
Nice. Then I am happy with the pr as well. :+1:

**Comment by ipa-rmb** [comment]
Visual Review OK

**Pull request merged**
